export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transaction with zero fees',
    descreption: 'Get access to our exclusive app that allows you to send unlimited transaction without getting charged any fees.',
    buttonLabel: 'Get Started',
    imgStart: false, 
    img: 'https://svgshare.com/i/R4j.svg',
    alt: 'Car',
    dark: true, 
    primary: true,
    darkText: false,
    color: '#f7f8fa',
};


export const homeObjTwo = {
    id: 'discover',
    color: '#010606',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Unlimited access',
    headline: 'Login to your account at any time ',
    descreption: 'We have you covered no matter where you are located. All you need is an internet connection and a phone or computer. ',
    buttonLabel: 'Learn More',
    imgStart: true, 
    img: 'https://svgshare.com/i/R4k.svg',
    alt: 'Piggybank',
    dark: false, 
    primary: false,
    darkText: true,
};
export const homeObjThree = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Join our Team ',
    headline: 'Creating account is axtremly easy',
    descreption: "Get everything set up and ready in under 10 minutes. All you need to do is add your information and you're ready to go. ",
    buttonLabel: 'Start now',
    imgStart: false, 
    img: 'https://svgshare.com/i/R6J.svg',
    alt: 'Secure data',
    dark: false, 
    primary: false,
    darkText: true,
    color: '#010606',
};